/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.mysql.tables;


import com.syntax.sweagleapi.db.mysql.Indexes;
import com.syntax.sweagleapi.db.mysql.Keys;
import com.syntax.sweagleapi.db.mysql.Mysql;
import com.syntax.sweagleapi.db.mysql.tables.records.SlaveRelayLogInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * Relay Log Information
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaveRelayLogInfo extends TableImpl<SlaveRelayLogInfoRecord> {

    private static final long serialVersionUID = -763503551;

    /**
     * The reference instance of <code>mysql.slave_relay_log_info</code>
     */
    public static final SlaveRelayLogInfo SLAVE_RELAY_LOG_INFO = new SlaveRelayLogInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SlaveRelayLogInfoRecord> getRecordType() {
        return SlaveRelayLogInfoRecord.class;
    }

    /**
     * The column <code>mysql.slave_relay_log_info.Number_of_lines</code>. Number of lines in the file or rows in the table. Used to version table definitions.
     */
    public final TableField<SlaveRelayLogInfoRecord, UInteger> NUMBER_OF_LINES = createField("Number_of_lines", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Number of lines in the file or rows in the table. Used to version table definitions.");

    /**
     * The column <code>mysql.slave_relay_log_info.Relay_log_name</code>. The name of the current relay log file.
     */
    public final TableField<SlaveRelayLogInfoRecord, String> RELAY_LOG_NAME = createField("Relay_log_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "The name of the current relay log file.");

    /**
     * The column <code>mysql.slave_relay_log_info.Relay_log_pos</code>. The relay log position of the last executed event.
     */
    public final TableField<SlaveRelayLogInfoRecord, ULong> RELAY_LOG_POS = createField("Relay_log_pos", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "The relay log position of the last executed event.");

    /**
     * The column <code>mysql.slave_relay_log_info.Master_log_name</code>. The name of the master binary log file from which the events in the relay log file were read.
     */
    public final TableField<SlaveRelayLogInfoRecord, String> MASTER_LOG_NAME = createField("Master_log_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "The name of the master binary log file from which the events in the relay log file were read.");

    /**
     * The column <code>mysql.slave_relay_log_info.Master_log_pos</code>. The master log position of the last executed event.
     */
    public final TableField<SlaveRelayLogInfoRecord, ULong> MASTER_LOG_POS = createField("Master_log_pos", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "The master log position of the last executed event.");

    /**
     * The column <code>mysql.slave_relay_log_info.Sql_delay</code>. The number of seconds that the slave must lag behind the master.
     */
    public final TableField<SlaveRelayLogInfoRecord, Integer> SQL_DELAY = createField("Sql_delay", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "The number of seconds that the slave must lag behind the master.");

    /**
     * The column <code>mysql.slave_relay_log_info.Number_of_workers</code>.
     */
    public final TableField<SlaveRelayLogInfoRecord, UInteger> NUMBER_OF_WORKERS = createField("Number_of_workers", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>mysql.slave_relay_log_info.Id</code>. Internal Id that uniquely identifies this record.
     */
    public final TableField<SlaveRelayLogInfoRecord, UInteger> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Internal Id that uniquely identifies this record.");

    /**
     * The column <code>mysql.slave_relay_log_info.Channel_name</code>. The channel on which the slave is connected to a source. Used in Multisource Replication
     */
    public final TableField<SlaveRelayLogInfoRecord, String> CHANNEL_NAME = createField("Channel_name", org.jooq.impl.SQLDataType.CHAR(64).nullable(false), this, "The channel on which the slave is connected to a source. Used in Multisource Replication");

    /**
     * The column <code>mysql.slave_relay_log_info.Privilege_checks_username</code>. Username part of PRIVILEGE_CHECKS_USER.
     */
    public final TableField<SlaveRelayLogInfoRecord, String> PRIVILEGE_CHECKS_USERNAME = createField("Privilege_checks_username", org.jooq.impl.SQLDataType.CHAR(32), this, "Username part of PRIVILEGE_CHECKS_USER.");

    /**
     * The column <code>mysql.slave_relay_log_info.Privilege_checks_hostname</code>. Hostname part of PRIVILEGE_CHECKS_USER.
     */
    public final TableField<SlaveRelayLogInfoRecord, String> PRIVILEGE_CHECKS_HOSTNAME = createField("Privilege_checks_hostname", org.jooq.impl.SQLDataType.CHAR(255), this, "Hostname part of PRIVILEGE_CHECKS_USER.");

    /**
     * Create a <code>mysql.slave_relay_log_info</code> table reference
     */
    public SlaveRelayLogInfo() {
        this(DSL.name("slave_relay_log_info"), null);
    }

    /**
     * Create an aliased <code>mysql.slave_relay_log_info</code> table reference
     */
    public SlaveRelayLogInfo(String alias) {
        this(DSL.name(alias), SLAVE_RELAY_LOG_INFO);
    }

    /**
     * Create an aliased <code>mysql.slave_relay_log_info</code> table reference
     */
    public SlaveRelayLogInfo(Name alias) {
        this(alias, SLAVE_RELAY_LOG_INFO);
    }

    private SlaveRelayLogInfo(Name alias, Table<SlaveRelayLogInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private SlaveRelayLogInfo(Name alias, Table<SlaveRelayLogInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Relay Log Information"));
    }

    public <O extends Record> SlaveRelayLogInfo(Table<O> child, ForeignKey<O, SlaveRelayLogInfoRecord> key) {
        super(child, key, SLAVE_RELAY_LOG_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mysql.MYSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SLAVE_RELAY_LOG_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SlaveRelayLogInfoRecord> getPrimaryKey() {
        return Keys.KEY_SLAVE_RELAY_LOG_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SlaveRelayLogInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<SlaveRelayLogInfoRecord>>asList(Keys.KEY_SLAVE_RELAY_LOG_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfo as(String alias) {
        return new SlaveRelayLogInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaveRelayLogInfo as(Name alias) {
        return new SlaveRelayLogInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SlaveRelayLogInfo rename(String name) {
        return new SlaveRelayLogInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SlaveRelayLogInfo rename(Name name) {
        return new SlaveRelayLogInfo(name, null);
    }
}
