/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.mysql;


import com.syntax.sweagleapi.db.mysql.tables.ColumnsPriv;
import com.syntax.sweagleapi.db.mysql.tables.Component;
import com.syntax.sweagleapi.db.mysql.tables.Db;
import com.syntax.sweagleapi.db.mysql.tables.DefaultRoles;
import com.syntax.sweagleapi.db.mysql.tables.EngineCost;
import com.syntax.sweagleapi.db.mysql.tables.Func;
import com.syntax.sweagleapi.db.mysql.tables.GlobalGrants;
import com.syntax.sweagleapi.db.mysql.tables.GtidExecuted;
import com.syntax.sweagleapi.db.mysql.tables.HelpCategory;
import com.syntax.sweagleapi.db.mysql.tables.HelpKeyword;
import com.syntax.sweagleapi.db.mysql.tables.HelpRelation;
import com.syntax.sweagleapi.db.mysql.tables.HelpTopic;
import com.syntax.sweagleapi.db.mysql.tables.InnodbIndexStats;
import com.syntax.sweagleapi.db.mysql.tables.InnodbTableStats;
import com.syntax.sweagleapi.db.mysql.tables.PasswordHistory;
import com.syntax.sweagleapi.db.mysql.tables.Plugin;
import com.syntax.sweagleapi.db.mysql.tables.ProcsPriv;
import com.syntax.sweagleapi.db.mysql.tables.ProxiesPriv;
import com.syntax.sweagleapi.db.mysql.tables.RoleEdges;
import com.syntax.sweagleapi.db.mysql.tables.ServerCost;
import com.syntax.sweagleapi.db.mysql.tables.Servers;
import com.syntax.sweagleapi.db.mysql.tables.SlaveMasterInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveRelayLogInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveWorkerInfo;
import com.syntax.sweagleapi.db.mysql.tables.TablesPriv;
import com.syntax.sweagleapi.db.mysql.tables.TimeZone;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneLeapSecond;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneName;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransition;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransitionType;
import com.syntax.sweagleapi.db.mysql.tables.User;
import com.syntax.sweagleapi.db.mysql.tables.records.ColumnsPrivRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.ComponentRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.DbRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.DefaultRolesRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.EngineCostRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.FuncRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.GlobalGrantsRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.GtidExecutedRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.HelpCategoryRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.HelpKeywordRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.HelpRelationRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.HelpTopicRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.InnodbIndexStatsRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.InnodbTableStatsRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.PasswordHistoryRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.PluginRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.ProcsPrivRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.ProxiesPrivRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.RoleEdgesRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.ServerCostRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.ServersRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.SlaveMasterInfoRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.SlaveRelayLogInfoRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.SlaveWorkerInfoRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TablesPrivRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TimeZoneLeapSecondRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TimeZoneNameRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TimeZoneRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TimeZoneTransitionRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.TimeZoneTransitionTypeRecord;
import com.syntax.sweagleapi.db.mysql.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>mysql</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ComponentRecord, UInteger> IDENTITY_COMPONENT = Identities0.IDENTITY_COMPONENT;
    public static final Identity<TimeZoneRecord, UInteger> IDENTITY_TIME_ZONE = Identities0.IDENTITY_TIME_ZONE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ColumnsPrivRecord> KEY_COLUMNS_PRIV_PRIMARY = UniqueKeys0.KEY_COLUMNS_PRIV_PRIMARY;
    public static final UniqueKey<ComponentRecord> KEY_COMPONENT_PRIMARY = UniqueKeys0.KEY_COMPONENT_PRIMARY;
    public static final UniqueKey<DbRecord> KEY_DB_PRIMARY = UniqueKeys0.KEY_DB_PRIMARY;
    public static final UniqueKey<DefaultRolesRecord> KEY_DEFAULT_ROLES_PRIMARY = UniqueKeys0.KEY_DEFAULT_ROLES_PRIMARY;
    public static final UniqueKey<EngineCostRecord> KEY_ENGINE_COST_PRIMARY = UniqueKeys0.KEY_ENGINE_COST_PRIMARY;
    public static final UniqueKey<FuncRecord> KEY_FUNC_PRIMARY = UniqueKeys0.KEY_FUNC_PRIMARY;
    public static final UniqueKey<GlobalGrantsRecord> KEY_GLOBAL_GRANTS_PRIMARY = UniqueKeys0.KEY_GLOBAL_GRANTS_PRIMARY;
    public static final UniqueKey<GtidExecutedRecord> KEY_GTID_EXECUTED_PRIMARY = UniqueKeys0.KEY_GTID_EXECUTED_PRIMARY;
    public static final UniqueKey<HelpCategoryRecord> KEY_HELP_CATEGORY_PRIMARY = UniqueKeys0.KEY_HELP_CATEGORY_PRIMARY;
    public static final UniqueKey<HelpCategoryRecord> KEY_HELP_CATEGORY_NAME = UniqueKeys0.KEY_HELP_CATEGORY_NAME;
    public static final UniqueKey<HelpKeywordRecord> KEY_HELP_KEYWORD_PRIMARY = UniqueKeys0.KEY_HELP_KEYWORD_PRIMARY;
    public static final UniqueKey<HelpKeywordRecord> KEY_HELP_KEYWORD_NAME = UniqueKeys0.KEY_HELP_KEYWORD_NAME;
    public static final UniqueKey<HelpRelationRecord> KEY_HELP_RELATION_PRIMARY = UniqueKeys0.KEY_HELP_RELATION_PRIMARY;
    public static final UniqueKey<HelpTopicRecord> KEY_HELP_TOPIC_PRIMARY = UniqueKeys0.KEY_HELP_TOPIC_PRIMARY;
    public static final UniqueKey<HelpTopicRecord> KEY_HELP_TOPIC_NAME = UniqueKeys0.KEY_HELP_TOPIC_NAME;
    public static final UniqueKey<InnodbIndexStatsRecord> KEY_INNODB_INDEX_STATS_PRIMARY = UniqueKeys0.KEY_INNODB_INDEX_STATS_PRIMARY;
    public static final UniqueKey<InnodbTableStatsRecord> KEY_INNODB_TABLE_STATS_PRIMARY = UniqueKeys0.KEY_INNODB_TABLE_STATS_PRIMARY;
    public static final UniqueKey<PasswordHistoryRecord> KEY_PASSWORD_HISTORY_PRIMARY = UniqueKeys0.KEY_PASSWORD_HISTORY_PRIMARY;
    public static final UniqueKey<PluginRecord> KEY_PLUGIN_PRIMARY = UniqueKeys0.KEY_PLUGIN_PRIMARY;
    public static final UniqueKey<ProcsPrivRecord> KEY_PROCS_PRIV_PRIMARY = UniqueKeys0.KEY_PROCS_PRIV_PRIMARY;
    public static final UniqueKey<ProxiesPrivRecord> KEY_PROXIES_PRIV_PRIMARY = UniqueKeys0.KEY_PROXIES_PRIV_PRIMARY;
    public static final UniqueKey<RoleEdgesRecord> KEY_ROLE_EDGES_PRIMARY = UniqueKeys0.KEY_ROLE_EDGES_PRIMARY;
    public static final UniqueKey<ServerCostRecord> KEY_SERVER_COST_PRIMARY = UniqueKeys0.KEY_SERVER_COST_PRIMARY;
    public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = UniqueKeys0.KEY_SERVERS_PRIMARY;
    public static final UniqueKey<SlaveMasterInfoRecord> KEY_SLAVE_MASTER_INFO_PRIMARY = UniqueKeys0.KEY_SLAVE_MASTER_INFO_PRIMARY;
    public static final UniqueKey<SlaveRelayLogInfoRecord> KEY_SLAVE_RELAY_LOG_INFO_PRIMARY = UniqueKeys0.KEY_SLAVE_RELAY_LOG_INFO_PRIMARY;
    public static final UniqueKey<SlaveWorkerInfoRecord> KEY_SLAVE_WORKER_INFO_PRIMARY = UniqueKeys0.KEY_SLAVE_WORKER_INFO_PRIMARY;
    public static final UniqueKey<TablesPrivRecord> KEY_TABLES_PRIV_PRIMARY = UniqueKeys0.KEY_TABLES_PRIV_PRIMARY;
    public static final UniqueKey<TimeZoneRecord> KEY_TIME_ZONE_PRIMARY = UniqueKeys0.KEY_TIME_ZONE_PRIMARY;
    public static final UniqueKey<TimeZoneLeapSecondRecord> KEY_TIME_ZONE_LEAP_SECOND_PRIMARY = UniqueKeys0.KEY_TIME_ZONE_LEAP_SECOND_PRIMARY;
    public static final UniqueKey<TimeZoneNameRecord> KEY_TIME_ZONE_NAME_PRIMARY = UniqueKeys0.KEY_TIME_ZONE_NAME_PRIMARY;
    public static final UniqueKey<TimeZoneTransitionRecord> KEY_TIME_ZONE_TRANSITION_PRIMARY = UniqueKeys0.KEY_TIME_ZONE_TRANSITION_PRIMARY;
    public static final UniqueKey<TimeZoneTransitionTypeRecord> KEY_TIME_ZONE_TRANSITION_TYPE_PRIMARY = UniqueKeys0.KEY_TIME_ZONE_TRANSITION_TYPE_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ComponentRecord, UInteger> IDENTITY_COMPONENT = Internal.createIdentity(Component.COMPONENT, Component.COMPONENT.COMPONENT_ID);
        public static Identity<TimeZoneRecord, UInteger> IDENTITY_TIME_ZONE = Internal.createIdentity(TimeZone.TIME_ZONE, TimeZone.TIME_ZONE.TIME_ZONE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ColumnsPrivRecord> KEY_COLUMNS_PRIV_PRIMARY = Internal.createUniqueKey(ColumnsPriv.COLUMNS_PRIV, "KEY_columns_priv_PRIMARY", ColumnsPriv.COLUMNS_PRIV.HOST, ColumnsPriv.COLUMNS_PRIV.DB, ColumnsPriv.COLUMNS_PRIV.USER, ColumnsPriv.COLUMNS_PRIV.TABLE_NAME, ColumnsPriv.COLUMNS_PRIV.COLUMN_NAME);
        public static final UniqueKey<ComponentRecord> KEY_COMPONENT_PRIMARY = Internal.createUniqueKey(Component.COMPONENT, "KEY_component_PRIMARY", Component.COMPONENT.COMPONENT_ID);
        public static final UniqueKey<DbRecord> KEY_DB_PRIMARY = Internal.createUniqueKey(Db.DB, "KEY_db_PRIMARY", Db.DB.HOST, Db.DB.DB_, Db.DB.USER);
        public static final UniqueKey<DefaultRolesRecord> KEY_DEFAULT_ROLES_PRIMARY = Internal.createUniqueKey(DefaultRoles.DEFAULT_ROLES, "KEY_default_roles_PRIMARY", DefaultRoles.DEFAULT_ROLES.HOST, DefaultRoles.DEFAULT_ROLES.USER, DefaultRoles.DEFAULT_ROLES.DEFAULT_ROLE_HOST, DefaultRoles.DEFAULT_ROLES.DEFAULT_ROLE_USER);
        public static final UniqueKey<EngineCostRecord> KEY_ENGINE_COST_PRIMARY = Internal.createUniqueKey(EngineCost.ENGINE_COST, "KEY_engine_cost_PRIMARY", EngineCost.ENGINE_COST.COST_NAME, EngineCost.ENGINE_COST.ENGINE_NAME, EngineCost.ENGINE_COST.DEVICE_TYPE);
        public static final UniqueKey<FuncRecord> KEY_FUNC_PRIMARY = Internal.createUniqueKey(Func.FUNC, "KEY_func_PRIMARY", Func.FUNC.NAME);
        public static final UniqueKey<GlobalGrantsRecord> KEY_GLOBAL_GRANTS_PRIMARY = Internal.createUniqueKey(GlobalGrants.GLOBAL_GRANTS, "KEY_global_grants_PRIMARY", GlobalGrants.GLOBAL_GRANTS.USER, GlobalGrants.GLOBAL_GRANTS.HOST, GlobalGrants.GLOBAL_GRANTS.PRIV);
        public static final UniqueKey<GtidExecutedRecord> KEY_GTID_EXECUTED_PRIMARY = Internal.createUniqueKey(GtidExecuted.GTID_EXECUTED, "KEY_gtid_executed_PRIMARY", GtidExecuted.GTID_EXECUTED.SOURCE_UUID, GtidExecuted.GTID_EXECUTED.INTERVAL_START);
        public static final UniqueKey<HelpCategoryRecord> KEY_HELP_CATEGORY_PRIMARY = Internal.createUniqueKey(HelpCategory.HELP_CATEGORY, "KEY_help_category_PRIMARY", HelpCategory.HELP_CATEGORY.HELP_CATEGORY_ID);
        public static final UniqueKey<HelpCategoryRecord> KEY_HELP_CATEGORY_NAME = Internal.createUniqueKey(HelpCategory.HELP_CATEGORY, "KEY_help_category_name", HelpCategory.HELP_CATEGORY.NAME);
        public static final UniqueKey<HelpKeywordRecord> KEY_HELP_KEYWORD_PRIMARY = Internal.createUniqueKey(HelpKeyword.HELP_KEYWORD, "KEY_help_keyword_PRIMARY", HelpKeyword.HELP_KEYWORD.HELP_KEYWORD_ID);
        public static final UniqueKey<HelpKeywordRecord> KEY_HELP_KEYWORD_NAME = Internal.createUniqueKey(HelpKeyword.HELP_KEYWORD, "KEY_help_keyword_name", HelpKeyword.HELP_KEYWORD.NAME);
        public static final UniqueKey<HelpRelationRecord> KEY_HELP_RELATION_PRIMARY = Internal.createUniqueKey(HelpRelation.HELP_RELATION, "KEY_help_relation_PRIMARY", HelpRelation.HELP_RELATION.HELP_KEYWORD_ID, HelpRelation.HELP_RELATION.HELP_TOPIC_ID);
        public static final UniqueKey<HelpTopicRecord> KEY_HELP_TOPIC_PRIMARY = Internal.createUniqueKey(HelpTopic.HELP_TOPIC, "KEY_help_topic_PRIMARY", HelpTopic.HELP_TOPIC.HELP_TOPIC_ID);
        public static final UniqueKey<HelpTopicRecord> KEY_HELP_TOPIC_NAME = Internal.createUniqueKey(HelpTopic.HELP_TOPIC, "KEY_help_topic_name", HelpTopic.HELP_TOPIC.NAME);
        public static final UniqueKey<InnodbIndexStatsRecord> KEY_INNODB_INDEX_STATS_PRIMARY = Internal.createUniqueKey(InnodbIndexStats.INNODB_INDEX_STATS, "KEY_innodb_index_stats_PRIMARY", InnodbIndexStats.INNODB_INDEX_STATS.DATABASE_NAME, InnodbIndexStats.INNODB_INDEX_STATS.TABLE_NAME, InnodbIndexStats.INNODB_INDEX_STATS.INDEX_NAME, InnodbIndexStats.INNODB_INDEX_STATS.STAT_NAME);
        public static final UniqueKey<InnodbTableStatsRecord> KEY_INNODB_TABLE_STATS_PRIMARY = Internal.createUniqueKey(InnodbTableStats.INNODB_TABLE_STATS, "KEY_innodb_table_stats_PRIMARY", InnodbTableStats.INNODB_TABLE_STATS.DATABASE_NAME, InnodbTableStats.INNODB_TABLE_STATS.TABLE_NAME);
        public static final UniqueKey<PasswordHistoryRecord> KEY_PASSWORD_HISTORY_PRIMARY = Internal.createUniqueKey(PasswordHistory.PASSWORD_HISTORY, "KEY_password_history_PRIMARY", PasswordHistory.PASSWORD_HISTORY.HOST, PasswordHistory.PASSWORD_HISTORY.USER, PasswordHistory.PASSWORD_HISTORY.PASSWORD_TIMESTAMP);
        public static final UniqueKey<PluginRecord> KEY_PLUGIN_PRIMARY = Internal.createUniqueKey(Plugin.PLUGIN, "KEY_plugin_PRIMARY", Plugin.PLUGIN.NAME);
        public static final UniqueKey<ProcsPrivRecord> KEY_PROCS_PRIV_PRIMARY = Internal.createUniqueKey(ProcsPriv.PROCS_PRIV, "KEY_procs_priv_PRIMARY", ProcsPriv.PROCS_PRIV.HOST, ProcsPriv.PROCS_PRIV.DB, ProcsPriv.PROCS_PRIV.USER, ProcsPriv.PROCS_PRIV.ROUTINE_NAME, ProcsPriv.PROCS_PRIV.ROUTINE_TYPE);
        public static final UniqueKey<ProxiesPrivRecord> KEY_PROXIES_PRIV_PRIMARY = Internal.createUniqueKey(ProxiesPriv.PROXIES_PRIV, "KEY_proxies_priv_PRIMARY", ProxiesPriv.PROXIES_PRIV.HOST, ProxiesPriv.PROXIES_PRIV.USER, ProxiesPriv.PROXIES_PRIV.PROXIED_HOST, ProxiesPriv.PROXIES_PRIV.PROXIED_USER);
        public static final UniqueKey<RoleEdgesRecord> KEY_ROLE_EDGES_PRIMARY = Internal.createUniqueKey(RoleEdges.ROLE_EDGES, "KEY_role_edges_PRIMARY", RoleEdges.ROLE_EDGES.FROM_HOST, RoleEdges.ROLE_EDGES.FROM_USER, RoleEdges.ROLE_EDGES.TO_HOST, RoleEdges.ROLE_EDGES.TO_USER);
        public static final UniqueKey<ServerCostRecord> KEY_SERVER_COST_PRIMARY = Internal.createUniqueKey(ServerCost.SERVER_COST, "KEY_server_cost_PRIMARY", ServerCost.SERVER_COST.COST_NAME);
        public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = Internal.createUniqueKey(Servers.SERVERS, "KEY_servers_PRIMARY", Servers.SERVERS.SERVER_NAME);
        public static final UniqueKey<SlaveMasterInfoRecord> KEY_SLAVE_MASTER_INFO_PRIMARY = Internal.createUniqueKey(SlaveMasterInfo.SLAVE_MASTER_INFO, "KEY_slave_master_info_PRIMARY", SlaveMasterInfo.SLAVE_MASTER_INFO.CHANNEL_NAME);
        public static final UniqueKey<SlaveRelayLogInfoRecord> KEY_SLAVE_RELAY_LOG_INFO_PRIMARY = Internal.createUniqueKey(SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO, "KEY_slave_relay_log_info_PRIMARY", SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO.CHANNEL_NAME);
        public static final UniqueKey<SlaveWorkerInfoRecord> KEY_SLAVE_WORKER_INFO_PRIMARY = Internal.createUniqueKey(SlaveWorkerInfo.SLAVE_WORKER_INFO, "KEY_slave_worker_info_PRIMARY", SlaveWorkerInfo.SLAVE_WORKER_INFO.CHANNEL_NAME, SlaveWorkerInfo.SLAVE_WORKER_INFO.ID);
        public static final UniqueKey<TablesPrivRecord> KEY_TABLES_PRIV_PRIMARY = Internal.createUniqueKey(TablesPriv.TABLES_PRIV, "KEY_tables_priv_PRIMARY", TablesPriv.TABLES_PRIV.HOST, TablesPriv.TABLES_PRIV.DB, TablesPriv.TABLES_PRIV.USER, TablesPriv.TABLES_PRIV.TABLE_NAME);
        public static final UniqueKey<TimeZoneRecord> KEY_TIME_ZONE_PRIMARY = Internal.createUniqueKey(TimeZone.TIME_ZONE, "KEY_time_zone_PRIMARY", TimeZone.TIME_ZONE.TIME_ZONE_ID);
        public static final UniqueKey<TimeZoneLeapSecondRecord> KEY_TIME_ZONE_LEAP_SECOND_PRIMARY = Internal.createUniqueKey(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND, "KEY_time_zone_leap_second_PRIMARY", TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND.TRANSITION_TIME);
        public static final UniqueKey<TimeZoneNameRecord> KEY_TIME_ZONE_NAME_PRIMARY = Internal.createUniqueKey(TimeZoneName.TIME_ZONE_NAME, "KEY_time_zone_name_PRIMARY", TimeZoneName.TIME_ZONE_NAME.NAME);
        public static final UniqueKey<TimeZoneTransitionRecord> KEY_TIME_ZONE_TRANSITION_PRIMARY = Internal.createUniqueKey(TimeZoneTransition.TIME_ZONE_TRANSITION, "KEY_time_zone_transition_PRIMARY", TimeZoneTransition.TIME_ZONE_TRANSITION.TIME_ZONE_ID, TimeZoneTransition.TIME_ZONE_TRANSITION.TRANSITION_TIME);
        public static final UniqueKey<TimeZoneTransitionTypeRecord> KEY_TIME_ZONE_TRANSITION_TYPE_PRIMARY = Internal.createUniqueKey(TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE, "KEY_time_zone_transition_type_PRIMARY", TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE.TIME_ZONE_ID, TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE.TRANSITION_TYPE_ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.HOST, User.USER.USER_);
    }
}
