/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.mysql;


import com.syntax.sweagleapi.db.DefaultCatalog;
import com.syntax.sweagleapi.db.mysql.tables.ColumnsPriv;
import com.syntax.sweagleapi.db.mysql.tables.Component;
import com.syntax.sweagleapi.db.mysql.tables.Db;
import com.syntax.sweagleapi.db.mysql.tables.DefaultRoles;
import com.syntax.sweagleapi.db.mysql.tables.EngineCost;
import com.syntax.sweagleapi.db.mysql.tables.Func;
import com.syntax.sweagleapi.db.mysql.tables.GeneralLog;
import com.syntax.sweagleapi.db.mysql.tables.GlobalGrants;
import com.syntax.sweagleapi.db.mysql.tables.GtidExecuted;
import com.syntax.sweagleapi.db.mysql.tables.HelpCategory;
import com.syntax.sweagleapi.db.mysql.tables.HelpKeyword;
import com.syntax.sweagleapi.db.mysql.tables.HelpRelation;
import com.syntax.sweagleapi.db.mysql.tables.HelpTopic;
import com.syntax.sweagleapi.db.mysql.tables.InnodbIndexStats;
import com.syntax.sweagleapi.db.mysql.tables.InnodbTableStats;
import com.syntax.sweagleapi.db.mysql.tables.PasswordHistory;
import com.syntax.sweagleapi.db.mysql.tables.Plugin;
import com.syntax.sweagleapi.db.mysql.tables.ProcsPriv;
import com.syntax.sweagleapi.db.mysql.tables.ProxiesPriv;
import com.syntax.sweagleapi.db.mysql.tables.RoleEdges;
import com.syntax.sweagleapi.db.mysql.tables.ServerCost;
import com.syntax.sweagleapi.db.mysql.tables.Servers;
import com.syntax.sweagleapi.db.mysql.tables.SlaveMasterInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveRelayLogInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveWorkerInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlowLog;
import com.syntax.sweagleapi.db.mysql.tables.TablesPriv;
import com.syntax.sweagleapi.db.mysql.tables.TimeZone;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneLeapSecond;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneName;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransition;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransitionType;
import com.syntax.sweagleapi.db.mysql.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mysql extends SchemaImpl {

    private static final long serialVersionUID = -458037040;

    /**
     * The reference instance of <code>mysql</code>
     */
    public static final Mysql MYSQL = new Mysql();

    /**
     * Column privileges
     */
    public final ColumnsPriv COLUMNS_PRIV = com.syntax.sweagleapi.db.mysql.tables.ColumnsPriv.COLUMNS_PRIV;

    /**
     * Components
     */
    public final Component COMPONENT = com.syntax.sweagleapi.db.mysql.tables.Component.COMPONENT;

    /**
     * Database privileges
     */
    public final Db DB = com.syntax.sweagleapi.db.mysql.tables.Db.DB;

    /**
     * Default roles
     */
    public final DefaultRoles DEFAULT_ROLES = com.syntax.sweagleapi.db.mysql.tables.DefaultRoles.DEFAULT_ROLES;

    /**
     * The table <code>mysql.engine_cost</code>.
     */
    public final EngineCost ENGINE_COST = com.syntax.sweagleapi.db.mysql.tables.EngineCost.ENGINE_COST;

    /**
     * User defined functions
     */
    public final Func FUNC = com.syntax.sweagleapi.db.mysql.tables.Func.FUNC;

    /**
     * General log
     */
    public final GeneralLog GENERAL_LOG = com.syntax.sweagleapi.db.mysql.tables.GeneralLog.GENERAL_LOG;

    /**
     * Extended global grants
     */
    public final GlobalGrants GLOBAL_GRANTS = com.syntax.sweagleapi.db.mysql.tables.GlobalGrants.GLOBAL_GRANTS;

    /**
     * The table <code>mysql.gtid_executed</code>.
     */
    public final GtidExecuted GTID_EXECUTED = com.syntax.sweagleapi.db.mysql.tables.GtidExecuted.GTID_EXECUTED;

    /**
     * help categories
     */
    public final HelpCategory HELP_CATEGORY = com.syntax.sweagleapi.db.mysql.tables.HelpCategory.HELP_CATEGORY;

    /**
     * help keywords
     */
    public final HelpKeyword HELP_KEYWORD = com.syntax.sweagleapi.db.mysql.tables.HelpKeyword.HELP_KEYWORD;

    /**
     * keyword-topic relation
     */
    public final HelpRelation HELP_RELATION = com.syntax.sweagleapi.db.mysql.tables.HelpRelation.HELP_RELATION;

    /**
     * help topics
     */
    public final HelpTopic HELP_TOPIC = com.syntax.sweagleapi.db.mysql.tables.HelpTopic.HELP_TOPIC;

    /**
     * The table <code>mysql.innodb_index_stats</code>.
     */
    public final InnodbIndexStats INNODB_INDEX_STATS = com.syntax.sweagleapi.db.mysql.tables.InnodbIndexStats.INNODB_INDEX_STATS;

    /**
     * The table <code>mysql.innodb_table_stats</code>.
     */
    public final InnodbTableStats INNODB_TABLE_STATS = com.syntax.sweagleapi.db.mysql.tables.InnodbTableStats.INNODB_TABLE_STATS;

    /**
     * Password history for user accounts
     */
    public final PasswordHistory PASSWORD_HISTORY = com.syntax.sweagleapi.db.mysql.tables.PasswordHistory.PASSWORD_HISTORY;

    /**
     * MySQL plugins
     */
    public final Plugin PLUGIN = com.syntax.sweagleapi.db.mysql.tables.Plugin.PLUGIN;

    /**
     * Procedure privileges
     */
    public final ProcsPriv PROCS_PRIV = com.syntax.sweagleapi.db.mysql.tables.ProcsPriv.PROCS_PRIV;

    /**
     * User proxy privileges
     */
    public final ProxiesPriv PROXIES_PRIV = com.syntax.sweagleapi.db.mysql.tables.ProxiesPriv.PROXIES_PRIV;

    /**
     * Role hierarchy and role grants
     */
    public final RoleEdges ROLE_EDGES = com.syntax.sweagleapi.db.mysql.tables.RoleEdges.ROLE_EDGES;

    /**
     * The table <code>mysql.server_cost</code>.
     */
    public final ServerCost SERVER_COST = com.syntax.sweagleapi.db.mysql.tables.ServerCost.SERVER_COST;

    /**
     * MySQL Foreign Servers table
     */
    public final Servers SERVERS = com.syntax.sweagleapi.db.mysql.tables.Servers.SERVERS;

    /**
     * Master Information
     */
    public final SlaveMasterInfo SLAVE_MASTER_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveMasterInfo.SLAVE_MASTER_INFO;

    /**
     * Relay Log Information
     */
    public final SlaveRelayLogInfo SLAVE_RELAY_LOG_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO;

    /**
     * Worker Information
     */
    public final SlaveWorkerInfo SLAVE_WORKER_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveWorkerInfo.SLAVE_WORKER_INFO;

    /**
     * Slow log
     */
    public final SlowLog SLOW_LOG = com.syntax.sweagleapi.db.mysql.tables.SlowLog.SLOW_LOG;

    /**
     * Table privileges
     */
    public final TablesPriv TABLES_PRIV = com.syntax.sweagleapi.db.mysql.tables.TablesPriv.TABLES_PRIV;

    /**
     * Time zones
     */
    public final TimeZone TIME_ZONE = com.syntax.sweagleapi.db.mysql.tables.TimeZone.TIME_ZONE;

    /**
     * Leap seconds information for time zones
     */
    public final TimeZoneLeapSecond TIME_ZONE_LEAP_SECOND = com.syntax.sweagleapi.db.mysql.tables.TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND;

    /**
     * Time zone names
     */
    public final TimeZoneName TIME_ZONE_NAME = com.syntax.sweagleapi.db.mysql.tables.TimeZoneName.TIME_ZONE_NAME;

    /**
     * Time zone transitions
     */
    public final TimeZoneTransition TIME_ZONE_TRANSITION = com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION;

    /**
     * Time zone transition types
     */
    public final TimeZoneTransitionType TIME_ZONE_TRANSITION_TYPE = com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE;

    /**
     * Users and global privileges
     */
    public final User USER = com.syntax.sweagleapi.db.mysql.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Mysql() {
        super("mysql", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ColumnsPriv.COLUMNS_PRIV,
            Component.COMPONENT,
            Db.DB,
            DefaultRoles.DEFAULT_ROLES,
            EngineCost.ENGINE_COST,
            Func.FUNC,
            GeneralLog.GENERAL_LOG,
            GlobalGrants.GLOBAL_GRANTS,
            GtidExecuted.GTID_EXECUTED,
            HelpCategory.HELP_CATEGORY,
            HelpKeyword.HELP_KEYWORD,
            HelpRelation.HELP_RELATION,
            HelpTopic.HELP_TOPIC,
            InnodbIndexStats.INNODB_INDEX_STATS,
            InnodbTableStats.INNODB_TABLE_STATS,
            PasswordHistory.PASSWORD_HISTORY,
            Plugin.PLUGIN,
            ProcsPriv.PROCS_PRIV,
            ProxiesPriv.PROXIES_PRIV,
            RoleEdges.ROLE_EDGES,
            ServerCost.SERVER_COST,
            Servers.SERVERS,
            SlaveMasterInfo.SLAVE_MASTER_INFO,
            SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO,
            SlaveWorkerInfo.SLAVE_WORKER_INFO,
            SlowLog.SLOW_LOG,
            TablesPriv.TABLES_PRIV,
            TimeZone.TIME_ZONE,
            TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND,
            TimeZoneName.TIME_ZONE_NAME,
            TimeZoneTransition.TIME_ZONE_TRANSITION,
            TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE,
            User.USER);
    }
}
