/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.mysql;


import com.syntax.sweagleapi.db.mysql.tables.ColumnsPriv;
import com.syntax.sweagleapi.db.mysql.tables.Component;
import com.syntax.sweagleapi.db.mysql.tables.Db;
import com.syntax.sweagleapi.db.mysql.tables.DefaultRoles;
import com.syntax.sweagleapi.db.mysql.tables.EngineCost;
import com.syntax.sweagleapi.db.mysql.tables.Func;
import com.syntax.sweagleapi.db.mysql.tables.GeneralLog;
import com.syntax.sweagleapi.db.mysql.tables.GlobalGrants;
import com.syntax.sweagleapi.db.mysql.tables.GtidExecuted;
import com.syntax.sweagleapi.db.mysql.tables.HelpCategory;
import com.syntax.sweagleapi.db.mysql.tables.HelpKeyword;
import com.syntax.sweagleapi.db.mysql.tables.HelpRelation;
import com.syntax.sweagleapi.db.mysql.tables.HelpTopic;
import com.syntax.sweagleapi.db.mysql.tables.InnodbIndexStats;
import com.syntax.sweagleapi.db.mysql.tables.InnodbTableStats;
import com.syntax.sweagleapi.db.mysql.tables.PasswordHistory;
import com.syntax.sweagleapi.db.mysql.tables.Plugin;
import com.syntax.sweagleapi.db.mysql.tables.ProcsPriv;
import com.syntax.sweagleapi.db.mysql.tables.ProxiesPriv;
import com.syntax.sweagleapi.db.mysql.tables.RoleEdges;
import com.syntax.sweagleapi.db.mysql.tables.ServerCost;
import com.syntax.sweagleapi.db.mysql.tables.Servers;
import com.syntax.sweagleapi.db.mysql.tables.SlaveMasterInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveRelayLogInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlaveWorkerInfo;
import com.syntax.sweagleapi.db.mysql.tables.SlowLog;
import com.syntax.sweagleapi.db.mysql.tables.TablesPriv;
import com.syntax.sweagleapi.db.mysql.tables.TimeZone;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneLeapSecond;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneName;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransition;
import com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransitionType;
import com.syntax.sweagleapi.db.mysql.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mysql
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Column privileges
     */
    public static final ColumnsPriv COLUMNS_PRIV = com.syntax.sweagleapi.db.mysql.tables.ColumnsPriv.COLUMNS_PRIV;

    /**
     * Components
     */
    public static final Component COMPONENT = com.syntax.sweagleapi.db.mysql.tables.Component.COMPONENT;

    /**
     * Database privileges
     */
    public static final Db DB = com.syntax.sweagleapi.db.mysql.tables.Db.DB;

    /**
     * Default roles
     */
    public static final DefaultRoles DEFAULT_ROLES = com.syntax.sweagleapi.db.mysql.tables.DefaultRoles.DEFAULT_ROLES;

    /**
     * The table <code>mysql.engine_cost</code>.
     */
    public static final EngineCost ENGINE_COST = com.syntax.sweagleapi.db.mysql.tables.EngineCost.ENGINE_COST;

    /**
     * User defined functions
     */
    public static final Func FUNC = com.syntax.sweagleapi.db.mysql.tables.Func.FUNC;

    /**
     * General log
     */
    public static final GeneralLog GENERAL_LOG = com.syntax.sweagleapi.db.mysql.tables.GeneralLog.GENERAL_LOG;

    /**
     * Extended global grants
     */
    public static final GlobalGrants GLOBAL_GRANTS = com.syntax.sweagleapi.db.mysql.tables.GlobalGrants.GLOBAL_GRANTS;

    /**
     * The table <code>mysql.gtid_executed</code>.
     */
    public static final GtidExecuted GTID_EXECUTED = com.syntax.sweagleapi.db.mysql.tables.GtidExecuted.GTID_EXECUTED;

    /**
     * help categories
     */
    public static final HelpCategory HELP_CATEGORY = com.syntax.sweagleapi.db.mysql.tables.HelpCategory.HELP_CATEGORY;

    /**
     * help keywords
     */
    public static final HelpKeyword HELP_KEYWORD = com.syntax.sweagleapi.db.mysql.tables.HelpKeyword.HELP_KEYWORD;

    /**
     * keyword-topic relation
     */
    public static final HelpRelation HELP_RELATION = com.syntax.sweagleapi.db.mysql.tables.HelpRelation.HELP_RELATION;

    /**
     * help topics
     */
    public static final HelpTopic HELP_TOPIC = com.syntax.sweagleapi.db.mysql.tables.HelpTopic.HELP_TOPIC;

    /**
     * The table <code>mysql.innodb_index_stats</code>.
     */
    public static final InnodbIndexStats INNODB_INDEX_STATS = com.syntax.sweagleapi.db.mysql.tables.InnodbIndexStats.INNODB_INDEX_STATS;

    /**
     * The table <code>mysql.innodb_table_stats</code>.
     */
    public static final InnodbTableStats INNODB_TABLE_STATS = com.syntax.sweagleapi.db.mysql.tables.InnodbTableStats.INNODB_TABLE_STATS;

    /**
     * Password history for user accounts
     */
    public static final PasswordHistory PASSWORD_HISTORY = com.syntax.sweagleapi.db.mysql.tables.PasswordHistory.PASSWORD_HISTORY;

    /**
     * MySQL plugins
     */
    public static final Plugin PLUGIN = com.syntax.sweagleapi.db.mysql.tables.Plugin.PLUGIN;

    /**
     * Procedure privileges
     */
    public static final ProcsPriv PROCS_PRIV = com.syntax.sweagleapi.db.mysql.tables.ProcsPriv.PROCS_PRIV;

    /**
     * User proxy privileges
     */
    public static final ProxiesPriv PROXIES_PRIV = com.syntax.sweagleapi.db.mysql.tables.ProxiesPriv.PROXIES_PRIV;

    /**
     * Role hierarchy and role grants
     */
    public static final RoleEdges ROLE_EDGES = com.syntax.sweagleapi.db.mysql.tables.RoleEdges.ROLE_EDGES;

    /**
     * The table <code>mysql.server_cost</code>.
     */
    public static final ServerCost SERVER_COST = com.syntax.sweagleapi.db.mysql.tables.ServerCost.SERVER_COST;

    /**
     * MySQL Foreign Servers table
     */
    public static final Servers SERVERS = com.syntax.sweagleapi.db.mysql.tables.Servers.SERVERS;

    /**
     * Master Information
     */
    public static final SlaveMasterInfo SLAVE_MASTER_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveMasterInfo.SLAVE_MASTER_INFO;

    /**
     * Relay Log Information
     */
    public static final SlaveRelayLogInfo SLAVE_RELAY_LOG_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO;

    /**
     * Worker Information
     */
    public static final SlaveWorkerInfo SLAVE_WORKER_INFO = com.syntax.sweagleapi.db.mysql.tables.SlaveWorkerInfo.SLAVE_WORKER_INFO;

    /**
     * Slow log
     */
    public static final SlowLog SLOW_LOG = com.syntax.sweagleapi.db.mysql.tables.SlowLog.SLOW_LOG;

    /**
     * Table privileges
     */
    public static final TablesPriv TABLES_PRIV = com.syntax.sweagleapi.db.mysql.tables.TablesPriv.TABLES_PRIV;

    /**
     * Time zones
     */
    public static final TimeZone TIME_ZONE = com.syntax.sweagleapi.db.mysql.tables.TimeZone.TIME_ZONE;

    /**
     * Leap seconds information for time zones
     */
    public static final TimeZoneLeapSecond TIME_ZONE_LEAP_SECOND = com.syntax.sweagleapi.db.mysql.tables.TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND;

    /**
     * Time zone names
     */
    public static final TimeZoneName TIME_ZONE_NAME = com.syntax.sweagleapi.db.mysql.tables.TimeZoneName.TIME_ZONE_NAME;

    /**
     * Time zone transitions
     */
    public static final TimeZoneTransition TIME_ZONE_TRANSITION = com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION;

    /**
     * Time zone transition types
     */
    public static final TimeZoneTransitionType TIME_ZONE_TRANSITION_TYPE = com.syntax.sweagleapi.db.mysql.tables.TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE;

    /**
     * Users and global privileges
     */
    public static final User USER = com.syntax.sweagleapi.db.mysql.tables.User.USER;
}
