/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sweagle.tables.records;


import com.syntax.sweagleapi.db.sweagle.tables.Payload;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayloadRecord extends UpdatableRecordImpl<PayloadRecord> implements Record5<Long, Timestamp, Timestamp, byte[], Long> {

    private static final long serialVersionUID = -1171175193;

    /**
     * Setter for <code>sweagle.payload.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sweagle.payload.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sweagle.payload.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>sweagle.payload.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>sweagle.payload.update_date</code>.
     */
    public void setUpdateDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>sweagle.payload.update_date</code>.
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>sweagle.payload.data</code>.
     */
    public void setData(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>sweagle.payload.data</code>.
     */
    public byte[] getData() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>sweagle.payload.dataset_id</code>.
     */
    public void setDatasetId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>sweagle.payload.dataset_id</code>.
     */
    public Long getDatasetId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, Timestamp, byte[], Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, Timestamp, byte[], Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Payload.PAYLOAD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Payload.PAYLOAD.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Payload.PAYLOAD.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return Payload.PAYLOAD.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Payload.PAYLOAD.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord value3(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord value4(byte... value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord value5(Long value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayloadRecord values(Long value1, Timestamp value2, Timestamp value3, byte[] value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayloadRecord
     */
    public PayloadRecord() {
        super(Payload.PAYLOAD);
    }

    /**
     * Create a detached, initialised PayloadRecord
     */
    public PayloadRecord(Long id, Timestamp createDate, Timestamp updateDate, byte[] data, Long datasetId) {
        super(Payload.PAYLOAD);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, data);
        set(4, datasetId);
    }
}
