/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.information_schema.tables;


import com.syntax.sweagleapi.db.information_schema.InformationSchema;
import com.syntax.sweagleapi.db.information_schema.enums.ResourceGroupsResourceGroupType;
import com.syntax.sweagleapi.db.information_schema.tables.records.ResourceGroupsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceGroups extends TableImpl<ResourceGroupsRecord> {

    private static final long serialVersionUID = 806671346;

    /**
     * The reference instance of <code>information_schema.RESOURCE_GROUPS</code>
     */
    public static final ResourceGroups RESOURCE_GROUPS = new ResourceGroups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResourceGroupsRecord> getRecordType() {
        return ResourceGroupsRecord.class;
    }

    /**
     * The column <code>information_schema.RESOURCE_GROUPS.RESOURCE_GROUP_NAME</code>.
     */
    public final TableField<ResourceGroupsRecord, String> RESOURCE_GROUP_NAME = createField("RESOURCE_GROUP_NAME", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>information_schema.RESOURCE_GROUPS.RESOURCE_GROUP_TYPE</code>.
     */
    public final TableField<ResourceGroupsRecord, ResourceGroupsResourceGroupType> RESOURCE_GROUP_TYPE = createField("RESOURCE_GROUP_TYPE", org.jooq.impl.SQLDataType.VARCHAR(6).nullable(false).asEnumDataType(com.syntax.sweagleapi.db.information_schema.enums.ResourceGroupsResourceGroupType.class), this, "");

    /**
     * The column <code>information_schema.RESOURCE_GROUPS.RESOURCE_GROUP_ENABLED</code>.
     */
    public final TableField<ResourceGroupsRecord, Byte> RESOURCE_GROUP_ENABLED = createField("RESOURCE_GROUP_ENABLED", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>information_schema.RESOURCE_GROUPS.VCPU_IDS</code>.
     */
    public final TableField<ResourceGroupsRecord, byte[]> VCPU_IDS = createField("VCPU_IDS", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>information_schema.RESOURCE_GROUPS.THREAD_PRIORITY</code>.
     */
    public final TableField<ResourceGroupsRecord, Integer> THREAD_PRIORITY = createField("THREAD_PRIORITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>information_schema.RESOURCE_GROUPS</code> table reference
     */
    public ResourceGroups() {
        this(DSL.name("RESOURCE_GROUPS"), null);
    }

    /**
     * Create an aliased <code>information_schema.RESOURCE_GROUPS</code> table reference
     */
    public ResourceGroups(String alias) {
        this(DSL.name(alias), RESOURCE_GROUPS);
    }

    /**
     * Create an aliased <code>information_schema.RESOURCE_GROUPS</code> table reference
     */
    public ResourceGroups(Name alias) {
        this(alias, RESOURCE_GROUPS);
    }

    private ResourceGroups(Name alias, Table<ResourceGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResourceGroups(Name alias, Table<ResourceGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ResourceGroups(Table<O> child, ForeignKey<O, ResourceGroupsRecord> key) {
        super(child, key, RESOURCE_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResourceGroups as(String alias) {
        return new ResourceGroups(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResourceGroups as(Name alias) {
        return new ResourceGroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceGroups rename(String name) {
        return new ResourceGroups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceGroups rename(Name name) {
        return new ResourceGroups(name, null);
    }
}
