/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.performance_schema.tables;


import com.syntax.sweagleapi.db.performance_schema.Indexes;
import com.syntax.sweagleapi.db.performance_schema.Keys;
import com.syntax.sweagleapi.db.performance_schema.PerformanceSchema;
import com.syntax.sweagleapi.db.performance_schema.tables.records.ReplicationApplierConfigurationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReplicationApplierConfiguration extends TableImpl<ReplicationApplierConfigurationRecord> {

    private static final long serialVersionUID = 851790572;

    /**
     * The reference instance of <code>performance_schema.replication_applier_configuration</code>
     */
    public static final ReplicationApplierConfiguration REPLICATION_APPLIER_CONFIGURATION = new ReplicationApplierConfiguration();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReplicationApplierConfigurationRecord> getRecordType() {
        return ReplicationApplierConfigurationRecord.class;
    }

    /**
     * The column <code>performance_schema.replication_applier_configuration.CHANNEL_NAME</code>.
     */
    public final TableField<ReplicationApplierConfigurationRecord, String> CHANNEL_NAME = createField("CHANNEL_NAME", org.jooq.impl.SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>performance_schema.replication_applier_configuration.DESIRED_DELAY</code>.
     */
    public final TableField<ReplicationApplierConfigurationRecord, Integer> DESIRED_DELAY = createField("DESIRED_DELAY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>performance_schema.replication_applier_configuration.PRIVILEGE_CHECKS_USER</code>. User name for the security context of the applier.
     */
    public final TableField<ReplicationApplierConfigurationRecord, String> PRIVILEGE_CHECKS_USER = createField("PRIVILEGE_CHECKS_USER", org.jooq.impl.SQLDataType.CLOB, this, "User name for the security context of the applier.");

    /**
     * Create a <code>performance_schema.replication_applier_configuration</code> table reference
     */
    public ReplicationApplierConfiguration() {
        this(DSL.name("replication_applier_configuration"), null);
    }

    /**
     * Create an aliased <code>performance_schema.replication_applier_configuration</code> table reference
     */
    public ReplicationApplierConfiguration(String alias) {
        this(DSL.name(alias), REPLICATION_APPLIER_CONFIGURATION);
    }

    /**
     * Create an aliased <code>performance_schema.replication_applier_configuration</code> table reference
     */
    public ReplicationApplierConfiguration(Name alias) {
        this(alias, REPLICATION_APPLIER_CONFIGURATION);
    }

    private ReplicationApplierConfiguration(Name alias, Table<ReplicationApplierConfigurationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReplicationApplierConfiguration(Name alias, Table<ReplicationApplierConfigurationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ReplicationApplierConfiguration(Table<O> child, ForeignKey<O, ReplicationApplierConfigurationRecord> key) {
        super(child, key, REPLICATION_APPLIER_CONFIGURATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.REPLICATION_APPLIER_CONFIGURATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReplicationApplierConfigurationRecord> getPrimaryKey() {
        return Keys.KEY_REPLICATION_APPLIER_CONFIGURATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReplicationApplierConfigurationRecord>> getKeys() {
        return Arrays.<UniqueKey<ReplicationApplierConfigurationRecord>>asList(Keys.KEY_REPLICATION_APPLIER_CONFIGURATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfiguration as(String alias) {
        return new ReplicationApplierConfiguration(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfiguration as(Name alias) {
        return new ReplicationApplierConfiguration(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReplicationApplierConfiguration rename(String name) {
        return new ReplicationApplierConfiguration(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReplicationApplierConfiguration rename(Name name) {
        return new ReplicationApplierConfiguration(name, null);
    }
}
