/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.performance_schema.tables;


import com.syntax.sweagleapi.db.performance_schema.Indexes;
import com.syntax.sweagleapi.db.performance_schema.Keys;
import com.syntax.sweagleapi.db.performance_schema.PerformanceSchema;
import com.syntax.sweagleapi.db.performance_schema.enums.SetupConsumersEnabled;
import com.syntax.sweagleapi.db.performance_schema.tables.records.SetupConsumersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupConsumers extends TableImpl<SetupConsumersRecord> {

    private static final long serialVersionUID = 1733637335;

    /**
     * The reference instance of <code>performance_schema.setup_consumers</code>
     */
    public static final SetupConsumers SETUP_CONSUMERS = new SetupConsumers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetupConsumersRecord> getRecordType() {
        return SetupConsumersRecord.class;
    }

    /**
     * The column <code>performance_schema.setup_consumers.NAME</code>.
     */
    public final TableField<SetupConsumersRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>performance_schema.setup_consumers.ENABLED</code>.
     */
    public final TableField<SetupConsumersRecord, SetupConsumersEnabled> ENABLED = createField("ENABLED", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false).asEnumDataType(com.syntax.sweagleapi.db.performance_schema.enums.SetupConsumersEnabled.class), this, "");

    /**
     * Create a <code>performance_schema.setup_consumers</code> table reference
     */
    public SetupConsumers() {
        this(DSL.name("setup_consumers"), null);
    }

    /**
     * Create an aliased <code>performance_schema.setup_consumers</code> table reference
     */
    public SetupConsumers(String alias) {
        this(DSL.name(alias), SETUP_CONSUMERS);
    }

    /**
     * Create an aliased <code>performance_schema.setup_consumers</code> table reference
     */
    public SetupConsumers(Name alias) {
        this(alias, SETUP_CONSUMERS);
    }

    private SetupConsumers(Name alias, Table<SetupConsumersRecord> aliased) {
        this(alias, aliased, null);
    }

    private SetupConsumers(Name alias, Table<SetupConsumersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SetupConsumers(Table<O> child, ForeignKey<O, SetupConsumersRecord> key) {
        super(child, key, SETUP_CONSUMERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SETUP_CONSUMERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SetupConsumersRecord> getPrimaryKey() {
        return Keys.KEY_SETUP_CONSUMERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SetupConsumersRecord>> getKeys() {
        return Arrays.<UniqueKey<SetupConsumersRecord>>asList(Keys.KEY_SETUP_CONSUMERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupConsumers as(String alias) {
        return new SetupConsumers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupConsumers as(Name alias) {
        return new SetupConsumers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SetupConsumers rename(String name) {
        return new SetupConsumers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetupConsumers rename(Name name) {
        return new SetupConsumers(name, null);
    }
}
