/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sys.tables.records;


import com.syntax.sweagleapi.db.sys.tables.HostSummaryByStatementType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostSummaryByStatementTypeRecord extends TableRecordImpl<HostSummaryByStatementTypeRecord> implements Record10<String, String, ULong, String, String, String, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = -916191897;

    /**
     * Setter for <code>sys.host_summary_by_statement_type.host</code>.
     */
    public void setHost(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.host</code>.
     */
    public String getHost() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.statement</code>.
     */
    public void setStatement(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.statement</code>.
     */
    public String getStatement() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.total</code>.
     */
    public void setTotal(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.total</code>.
     */
    public ULong getTotal() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.total_latency</code>.
     */
    public void setTotalLatency(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.total_latency</code>.
     */
    public String getTotalLatency() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.max_latency</code>.
     */
    public void setMaxLatency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.max_latency</code>.
     */
    public String getMaxLatency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.lock_latency</code>.
     */
    public void setLockLatency(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.lock_latency</code>.
     */
    public String getLockLatency() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.rows_sent</code>.
     */
    public void setRowsSent(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.rows_sent</code>.
     */
    public ULong getRowsSent() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.rows_examined</code>.
     */
    public void setRowsExamined(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.rows_examined</code>.
     */
    public ULong getRowsExamined() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.rows_affected</code>.
     */
    public void setRowsAffected(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.rows_affected</code>.
     */
    public ULong getRowsAffected() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>sys.host_summary_by_statement_type.full_scans</code>.
     */
    public void setFullScans(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>sys.host_summary_by_statement_type.full_scans</code>.
     */
    public ULong getFullScans() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, ULong, String, String, String, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, ULong, String, String, String, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.HOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.STATEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.TOTAL_LATENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.MAX_LATENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.LOCK_LATENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.ROWS_SENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field8() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.ROWS_EXAMINED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field9() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.ROWS_AFFECTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field10() {
        return HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE.FULL_SCANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStatement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTotalLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMaxLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLockLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component7() {
        return getRowsSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component8() {
        return getRowsExamined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component9() {
        return getRowsAffected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component10() {
        return getFullScans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTotalLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMaxLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLockLatency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getRowsSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value8() {
        return getRowsExamined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value9() {
        return getRowsAffected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value10() {
        return getFullScans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value1(String value) {
        setHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value2(String value) {
        setStatement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value3(ULong value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value4(String value) {
        setTotalLatency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value5(String value) {
        setMaxLatency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value6(String value) {
        setLockLatency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value7(ULong value) {
        setRowsSent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value8(ULong value) {
        setRowsExamined(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value9(ULong value) {
        setRowsAffected(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord value10(ULong value) {
        setFullScans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSummaryByStatementTypeRecord values(String value1, String value2, ULong value3, String value4, String value5, String value6, ULong value7, ULong value8, ULong value9, ULong value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HostSummaryByStatementTypeRecord
     */
    public HostSummaryByStatementTypeRecord() {
        super(HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE);
    }

    /**
     * Create a detached, initialised HostSummaryByStatementTypeRecord
     */
    public HostSummaryByStatementTypeRecord(String host, String statement, ULong total, String totalLatency, String maxLatency, String lockLatency, ULong rowsSent, ULong rowsExamined, ULong rowsAffected, ULong fullScans) {
        super(HostSummaryByStatementType.HOST_SUMMARY_BY_STATEMENT_TYPE);

        set(0, host);
        set(1, statement);
        set(2, total);
        set(3, totalLatency);
        set(4, maxLatency);
        set(5, lockLatency);
        set(6, rowsSent);
        set(7, rowsExamined);
        set(8, rowsAffected);
        set(9, fullScans);
    }
}
