CREATE DATABASE sweagle;

USE sweagle;
 

CREATE TABLE DATASET (
  id       BIGINT    NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name     VARCHAR(50) NOT NULL,
  description      VARCHAR(50)
);

CREATE TABLE PAYLOAD (
  id       BIGINT    NOT NULL PRIMARY KEY AUTO_INCREMENT,
  create_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  data BLOB,
  dataset_id  BIGINT UNIQUE,
  FOREIGN KEY (dataset_id)  REFERENCES DATASET (id)  
);
