/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sys.tables;


import com.syntax.sweagleapi.db.sys.Sys;
import com.syntax.sweagleapi.db.sys.tables.records.X$hostSummaryByFileIoRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class X$hostSummaryByFileIo extends TableImpl<X$hostSummaryByFileIoRecord> {

    private static final long serialVersionUID = -74414085;

    /**
     * The reference instance of <code>sys.x$host_summary_by_file_io</code>
     */
    public static final X$hostSummaryByFileIo X$HOST_SUMMARY_BY_FILE_IO = new X$hostSummaryByFileIo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<X$hostSummaryByFileIoRecord> getRecordType() {
        return X$hostSummaryByFileIoRecord.class;
    }

    /**
     * The column <code>sys.x$host_summary_by_file_io.host</code>.
     */
    public final TableField<X$hostSummaryByFileIoRecord, String> HOST = createField("host", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>sys.x$host_summary_by_file_io.ios</code>.
     */
    public final TableField<X$hostSummaryByFileIoRecord, BigInteger> IOS = createField("ios", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

    /**
     * The column <code>sys.x$host_summary_by_file_io.io_latency</code>.
     */
    public final TableField<X$hostSummaryByFileIoRecord, BigInteger> IO_LATENCY = createField("io_latency", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

    /**
     * Create a <code>sys.x$host_summary_by_file_io</code> table reference
     */
    public X$hostSummaryByFileIo() {
        this(DSL.name("x$host_summary_by_file_io"), null);
    }

    /**
     * Create an aliased <code>sys.x$host_summary_by_file_io</code> table reference
     */
    public X$hostSummaryByFileIo(String alias) {
        this(DSL.name(alias), X$HOST_SUMMARY_BY_FILE_IO);
    }

    /**
     * Create an aliased <code>sys.x$host_summary_by_file_io</code> table reference
     */
    public X$hostSummaryByFileIo(Name alias) {
        this(alias, X$HOST_SUMMARY_BY_FILE_IO);
    }

    private X$hostSummaryByFileIo(Name alias, Table<X$hostSummaryByFileIoRecord> aliased) {
        this(alias, aliased, null);
    }

    private X$hostSummaryByFileIo(Name alias, Table<X$hostSummaryByFileIoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    public <O extends Record> X$hostSummaryByFileIo(Table<O> child, ForeignKey<O, X$hostSummaryByFileIoRecord> key) {
        super(child, key, X$HOST_SUMMARY_BY_FILE_IO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public X$hostSummaryByFileIo as(String alias) {
        return new X$hostSummaryByFileIo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public X$hostSummaryByFileIo as(Name alias) {
        return new X$hostSummaryByFileIo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public X$hostSummaryByFileIo rename(String name) {
        return new X$hostSummaryByFileIo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public X$hostSummaryByFileIo rename(Name name) {
        return new X$hostSummaryByFileIo(name, null);
    }
}
