/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sweagle;


import com.syntax.sweagleapi.db.sweagle.tables.Dataset;
import com.syntax.sweagleapi.db.sweagle.tables.Payload;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>sweagle</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATASET_PRIMARY = Indexes0.DATASET_PRIMARY;
    public static final Index PAYLOAD_DATASET_ID = Indexes0.PAYLOAD_DATASET_ID;
    public static final Index PAYLOAD_PRIMARY = Indexes0.PAYLOAD_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATASET_PRIMARY = Internal.createIndex("PRIMARY", Dataset.DATASET, new OrderField[] { Dataset.DATASET.ID }, true);
        public static Index PAYLOAD_DATASET_ID = Internal.createIndex("dataset_id", Payload.PAYLOAD, new OrderField[] { Payload.PAYLOAD.DATASET_ID }, true);
        public static Index PAYLOAD_PRIMARY = Internal.createIndex("PRIMARY", Payload.PAYLOAD, new OrderField[] { Payload.PAYLOAD.ID }, true);
    }
}
