/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sweagle;


import com.syntax.sweagleapi.db.sweagle.tables.Dataset;
import com.syntax.sweagleapi.db.sweagle.tables.Payload;
import com.syntax.sweagleapi.db.sweagle.tables.records.DatasetRecord;
import com.syntax.sweagleapi.db.sweagle.tables.records.PayloadRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>sweagle</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DatasetRecord, Long> IDENTITY_DATASET = Identities0.IDENTITY_DATASET;
    public static final Identity<PayloadRecord, Long> IDENTITY_PAYLOAD = Identities0.IDENTITY_PAYLOAD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatasetRecord> KEY_DATASET_PRIMARY = UniqueKeys0.KEY_DATASET_PRIMARY;
    public static final UniqueKey<PayloadRecord> KEY_PAYLOAD_PRIMARY = UniqueKeys0.KEY_PAYLOAD_PRIMARY;
    public static final UniqueKey<PayloadRecord> KEY_PAYLOAD_DATASET_ID = UniqueKeys0.KEY_PAYLOAD_DATASET_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PayloadRecord, DatasetRecord> PAYLOAD_IBFK_1 = ForeignKeys0.PAYLOAD_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DatasetRecord, Long> IDENTITY_DATASET = Internal.createIdentity(Dataset.DATASET, Dataset.DATASET.ID);
        public static Identity<PayloadRecord, Long> IDENTITY_PAYLOAD = Internal.createIdentity(Payload.PAYLOAD, Payload.PAYLOAD.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DatasetRecord> KEY_DATASET_PRIMARY = Internal.createUniqueKey(Dataset.DATASET, "KEY_dataset_PRIMARY", Dataset.DATASET.ID);
        public static final UniqueKey<PayloadRecord> KEY_PAYLOAD_PRIMARY = Internal.createUniqueKey(Payload.PAYLOAD, "KEY_payload_PRIMARY", Payload.PAYLOAD.ID);
        public static final UniqueKey<PayloadRecord> KEY_PAYLOAD_DATASET_ID = Internal.createUniqueKey(Payload.PAYLOAD, "KEY_payload_dataset_id", Payload.PAYLOAD.DATASET_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PayloadRecord, DatasetRecord> PAYLOAD_IBFK_1 = Internal.createForeignKey(com.syntax.sweagleapi.db.sweagle.Keys.KEY_DATASET_PRIMARY, Payload.PAYLOAD, "payload_ibfk_1", Payload.PAYLOAD.DATASET_ID);
    }
}
