/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sweagle;


import com.syntax.sweagleapi.db.DefaultCatalog;
import com.syntax.sweagleapi.db.sweagle.tables.Dataset;
import com.syntax.sweagleapi.db.sweagle.tables.Payload;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sweagle extends SchemaImpl {

    private static final long serialVersionUID = -100781905;

    /**
     * The reference instance of <code>sweagle</code>
     */
    public static final Sweagle SWEAGLE = new Sweagle();

    /**
     * The table <code>sweagle.dataset</code>.
     */
    public final Dataset DATASET = com.syntax.sweagleapi.db.sweagle.tables.Dataset.DATASET;

    /**
     * The table <code>sweagle.payload</code>.
     */
    public final Payload PAYLOAD = com.syntax.sweagleapi.db.sweagle.tables.Payload.PAYLOAD;

    /**
     * No further instances allowed
     */
    private Sweagle() {
        super("sweagle", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Dataset.DATASET,
            Payload.PAYLOAD);
    }
}
