/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.sweagle;


import com.syntax.sweagleapi.db.sweagle.tables.Dataset;
import com.syntax.sweagleapi.db.sweagle.tables.Payload;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sweagle
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sweagle.dataset</code>.
     */
    public static final Dataset DATASET = com.syntax.sweagleapi.db.sweagle.tables.Dataset.DATASET;

    /**
     * The table <code>sweagle.payload</code>.
     */
    public static final Payload PAYLOAD = com.syntax.sweagleapi.db.sweagle.tables.Payload.PAYLOAD;
}
