/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.performance_schema.tables.records;


import com.syntax.sweagleapi.db.performance_schema.tables.ReplicationApplierConfiguration;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReplicationApplierConfigurationRecord extends UpdatableRecordImpl<ReplicationApplierConfigurationRecord> implements Record3<String, Integer, String> {

    private static final long serialVersionUID = 104776996;

    /**
     * Setter for <code>performance_schema.replication_applier_configuration.CHANNEL_NAME</code>.
     */
    public void setChannelName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>performance_schema.replication_applier_configuration.CHANNEL_NAME</code>.
     */
    public String getChannelName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>performance_schema.replication_applier_configuration.DESIRED_DELAY</code>.
     */
    public void setDesiredDelay(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>performance_schema.replication_applier_configuration.DESIRED_DELAY</code>.
     */
    public Integer getDesiredDelay() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>performance_schema.replication_applier_configuration.PRIVILEGE_CHECKS_USER</code>. User name for the security context of the applier.
     */
    public void setPrivilegeChecksUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>performance_schema.replication_applier_configuration.PRIVILEGE_CHECKS_USER</code>. User name for the security context of the applier.
     */
    public String getPrivilegeChecksUser() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ReplicationApplierConfiguration.REPLICATION_APPLIER_CONFIGURATION.CHANNEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReplicationApplierConfiguration.REPLICATION_APPLIER_CONFIGURATION.DESIRED_DELAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ReplicationApplierConfiguration.REPLICATION_APPLIER_CONFIGURATION.PRIVILEGE_CHECKS_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDesiredDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrivilegeChecksUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChannelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDesiredDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrivilegeChecksUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfigurationRecord value1(String value) {
        setChannelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfigurationRecord value2(Integer value) {
        setDesiredDelay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfigurationRecord value3(String value) {
        setPrivilegeChecksUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplicationApplierConfigurationRecord values(String value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReplicationApplierConfigurationRecord
     */
    public ReplicationApplierConfigurationRecord() {
        super(ReplicationApplierConfiguration.REPLICATION_APPLIER_CONFIGURATION);
    }

    /**
     * Create a detached, initialised ReplicationApplierConfigurationRecord
     */
    public ReplicationApplierConfigurationRecord(String channelName, Integer desiredDelay, String privilegeChecksUser) {
        super(ReplicationApplierConfiguration.REPLICATION_APPLIER_CONFIGURATION);

        set(0, channelName);
        set(1, desiredDelay);
        set(2, privilegeChecksUser);
    }
}
