/*
 * This file is generated by jOOQ.
 */
package com.syntax.sweagleapi.db.performance_schema.enums;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PerformanceTimersTimerName implements EnumType {

    CYCLE("CYCLE"),

    NANOSECOND("NANOSECOND"),

    MICROSECOND("MICROSECOND"),

    MILLISECOND("MILLISECOND");

    private final String literal;

    private PerformanceTimersTimerName(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "performance_timers_TIMER_NAME";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
